# Generated by Django 2.1.7 on 2019-02-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='season',
            new_name='semester',
        ),
    ]
