# Generated by Django 2.1.7 on 2019-02-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratem', '0004_auto_20190225_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentcomment',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursecomment',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
