# Generated by Django 2.1.7 on 2019-02-25 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratem', '0005_auto_20190225_0449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentcomment',
            old_name='assingment',
            new_name='assignment',
        ),
    ]
