# Generated by Django 2.1.7 on 2019-02-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratem', '0006_auto_20190225_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.IntegerField(choices=[(0, 'Undergraduate'), (1, 'Graduate'), (2, 'Postgraduate')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
